### ISSUE TITLE
Upload is stuck in 100% CPU load

### ISSUE THREAD

**Issue by bjoernbusch** [SpellFoundry/Sleepy-Pi-Setup#1]
I have a Raspberry Pi 3 with Jessie and the Sleepy Pi2. I think I followed all the instructions, but somehow when I try to upload the blink example, the compile succeeds, but the upload never finishes and leaves the RPi "hanging" in 100% CPU load.

I tried to execute the steps from the manual, manually instead of the script, but no change. I installed a new SD card with a fresh Raspbian image and ran the script and got the same result.

Any suggestions what I might be doing wrong? Any info I could send you to debug this?

**Comment by devtin** [comment]
Hi @bjoernbusch. Have you been able to upload any other code to the Sleepy Pi2?

Make sure you either plug the power to the raspberry pi instead of the sleepy pi or you have the power bypass jumper on when uploading code to the sleepy pi from the raspberry pi.

**Comment by bjoernbusch** [comment]
I wasn't. I feel like the reset pin just isn't working. I wrote a simple python script, which should only trigger the reset pin and I would expect the Raspberry Pi to just shut off, since I don't have the jumper or software jumper in, but nothing happens.

I ordered another one to ensure that there is no hardware issue and I ordered the programming cable, but shipping is quite slow, so I'm just waiting now.

**Comment by devtin** [comment]
You know @bjoernbusch I once had the same issue and it wasn't the Sleepy Pi nor the setup script, but the raspberry pi (3) itself. I haven't been able to use that raspberry pi for uploading code for some reason, but with the same SD card in a different raspberry pi (3) it works. Perhaps some of the GPIO's are damaged.

**Comment by bjoernbusch** [comment]
I tried it on a Rpi3 and on a Rpi2, same thing :(

**Comment by bjoernbusch** [comment]
SleepyPi was broken.
